/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package turtle;

import java.awt.*;
import javax.swing.*;
import static java.awt.BorderLayout.CENTER;

/**
 *
 * @author Administrator
 */
public class TurtleWindow extends javax.swing.JInternalFrame
{
    private final DoubleBufferedTurtle turtle;

    /**
     * Creates new form LindenView
     * @param x
     * @param y
     */
    public TurtleWindow (int x, int y)
    {
        turtle = new DoubleBufferedTurtle (x, y);
        getContentPane().add (turtle, CENTER);
        initComponents();
    }
    
    /**
     * Get embedded Turtle
     * @return 
     */
    public DoubleBufferedTurtle getTurtle()
    {
        return turtle;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - unknown
    private void initComponents() {

        //======== this ========
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        Container contentPane = getContentPane();
        contentPane.setLayout(new BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - unknown
    // End of variables declaration//GEN-END:variables
}
