/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quran;

import java.awt.*;
import java.awt.event.*;
import java.beans.PropertyVetoException;
import javax.swing.*;
import applications.QuranGUI;
import misc.ComboBoxTools;

/**
 *
 * @author Administrator
 */
public class SeekResultGui extends javax.swing.JInternalFrame
{
    private QuranGUI m_source;
    
    /**
     * Creates new form SeekResultGui
     * @param q Master GUI
     * @param text String that is seeked for
     * @param res List of found positions
     */
    public SeekResultGui (QuranGUI q, String text, String[] res)
    {
        m_source = q;
        initComponents();
        this.setTitle(text);

        // Fill JList from String array
        ComboBoxTools.pollute (listControl, res);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - unknown
    private void initComponents() {
        jScrollPane1 = new JScrollPane();
        listControl = new JList<>();

        //======== this ========
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);
        setDoubleBuffered(true);
        setName("");
        try
        {
            setSelected(true);
        }
        catch (PropertyVetoException e)
        {
            e.printStackTrace();
        }
        Container contentPane = getContentPane();
        contentPane.setLayout(new BorderLayout());

        //======== jScrollPane1 ========
        {

            //---- listControl ----
            listControl.setModel(new AbstractListModel<String>() {
                String[] values = {
                    "Item 1",
                    "Item 2",
                    "Item 3",
                    "Item 4",
                    "Item 5"
                };
                @Override
                public int getSize() { return values.length; }
                @Override
                public String getElementAt(int i) { return values[i]; }
            });
            listControl.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    listControlMouseClicked(e);
                }
            });
            jScrollPane1.setViewportView(listControl);
        }
        contentPane.add(jScrollPane1, BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void listControlMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_listControlMouseClicked
    {//GEN-HEADEREND:event_listControlMouseClicked
        String v = (String)(listControl.getSelectedValue());
        m_source.display(v);
    }//GEN-LAST:event_listControlMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - unknown
    private JScrollPane jScrollPane1;
    private JList<String> listControl;
    // End of variables declaration//GEN-END:variables
}
