/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applications;

import chargen.Chargen;
import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.Serializable;
import misc.ClipboardImage;
import misc.MainWindow;
import misc.PittiFrame;
import misc.Tools;
import turtle.TurtleWindow;
import twitter.TwitTools;

/**
 *
 * @author Administrator
 */
public class C64TextGUI extends PittiFrame implements Serializable, ActionListener
{
    public static final long serialVersionUID = 1L;
    private transient TurtleWindow bitmapView = null;
    private transient Chargen chargen = new Chargen();
    
    /**
     * Initializer
     */
    {
        initComponents();
    }
    
    /**
     * Creates new form C64TextGUI
     */
    public C64TextGUI()
    {
    }

    private void createView (int x, int y)
    {
        if (bitmapView == null)
        {
            bitmapView = new TurtleWindow(x, y);
            MainWindow.instance.addChild(bitmapView);
        }
    }
    
    private void removeView()
    {
        if (bitmapView != null)
        {
            MainWindow.instance.remove(bitmapView);
            bitmapView.dispose();
            bitmapView = null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        inputText = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        saveName = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        messageTxt = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("C64Font");
        setMinimumSize(new java.awt.Dimension(550, 38));
        setPreferredSize(new java.awt.Dimension(499, 284));
        setVisible(true);

        inputText.setColumns(20);
        inputText.setRows(5);
        inputText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(inputText);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(491, 50));
        jPanel1.setLayout(null);

        jButton1.setText("Render");
        jButton1.addActionListener(this);
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 10, 75, 30);

        jButton7.setBackground(new java.awt.Color(255, 255, 0));
        jButton7.setText("Save as -->");
        jButton7.addActionListener(this);
        jPanel1.add(jButton7);
        jButton7.setBounds(390, 10, 120, 25);

        saveName.setText("C64Text");
        jPanel1.add(saveName);
        saveName.setBounds(510, 10, 160, 22);

        jButton2.setText("To Clip");
        jButton2.addActionListener(this);
        jPanel1.add(jButton2);
        jButton2.setBounds(90, 10, 90, 30);

        jButton4.setText("Tweet");
        jButton4.addActionListener(this);
        jPanel1.add(jButton4);
        jButton4.setBounds(250, 0, 71, 25);

        messageTxt.setText("C64_Font");
        jPanel1.add(messageTxt);
        messageTxt.setBounds(230, 30, 120, 22);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt)
    {
        if (evt.getSource() == jButton1)
        {
            C64TextGUI.this.jButton1ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton7)
        {
            C64TextGUI.this.jButton7ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton2)
        {
            C64TextGUI.this.jButton2ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton4)
        {
            C64TextGUI.this.jButton4ActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Render Button
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        if (chargen == null)
            chargen = new Chargen();
        String txt = inputText.getText();
        Dimension d = chargen.textParams (txt);
        
        removeView();
        createView (d.width, d.height);
        
        BufferedImage img = bitmapView.getTurtle().getImage();
        chargen.printImg (img, txt, 5, 5);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * Save the window
     * @param evt 
     */
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton7ActionPerformed
    {//GEN-HEADEREND:event_jButton7ActionPerformed
        try
        {
            Tools.serialize(saveName.getText(), this);
            MainWindow.instance.initSavesMenu();
        }
        catch (Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        if (bitmapView == null)
        {
            return;
        }

        BufferedImage img = bitmapView.getTurtle().getImage();
        try
        {
            TwitTools.get().send(img, messageTxt.getText());
        }
        catch (Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * To clipboard
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        BufferedImage img = bitmapView.getTurtle().getImage();
        new ClipboardImage (img);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea inputText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField messageTxt;
    private javax.swing.JTextField saveName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void initAfterDeserialization()
    {
        // Nix
    }
}
