package applications;

import misc.MDIChild;
import misc.MathParser;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.text.DecimalFormat;

/**
 * Created by Administrator on 11/15/2016.
 */
public class CalculatorGUI extends MDIChild
{
    private JTextArea outputArea;
    private JPanel panel1;
    private JTextField inputField;
    private DecimalFormat decimalFormat;

    public CalculatorGUI ()
    {
        super();

        decimalFormat = new DecimalFormat("##########.############################");

        this.add(panel1);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Math Tool");
        setSize(500, 300);
        setVisible(true);
        inputField.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed (ActionEvent e)
            {
                String s = inputField.getText();
                String sraw = s;
                s = s.replace("!", "!0");
                MathParser mathParser = new MathParser();
                mathParser.setFormula(s);
                BigDecimal b = mathParser.eval();
                String format = decimalFormat.format(b);
                inputField.setText("");
                if (outputArea.getText().length() == 0)
                {
                    s = "";
                }
                else
                {
                    s = "\n";
                }
                outputArea.append(s + sraw + " = " + format);
            }
        });
    }


    @Override
    public void initAfterDeserialization ()
    {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$ ()
    {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        outputArea = new JTextArea();
        panel1.add(outputArea, BorderLayout.CENTER);
        inputField = new JTextField();
        panel1.add(inputField, BorderLayout.SOUTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$ ()
    {
        return panel1;
    }
}
