/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applications;

import java.awt.*;
import javax.swing.*;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

/**
 *
 * @author Administrator
 */
public class ClockGUI extends javax.swing.JInternalFrame implements InternalFrameListener
{
    private clock.Clock m_clock;
    /**
     * Creates new form ClockGUI
     */
    public ClockGUI()
    {
        initComponents();
        setTitle("Analog Clock");
        m_clock = new clock.Clock();
        getContentPane().add(m_clock, java.awt.BorderLayout.CENTER);
        pack();
        addInternalFrameListener(this);
        setDefaultCloseOperation( WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - unknown
    private void initComponents() {

        //======== this ========
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setDoubleBuffered(true);
        Container contentPane = getContentPane();
        contentPane.setLayout(new BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void internalFrameOpened (InternalFrameEvent e)
    {

    }

    @Override
    public void internalFrameClosing (InternalFrameEvent e)
    {
        m_clock.shutdown();
        System.out.println("shutting down clock");
    }

    @Override
    public void internalFrameClosed (InternalFrameEvent e)
    {
    }

    @Override
    public void internalFrameIconified (InternalFrameEvent e)
    {

    }

    @Override
    public void internalFrameDeiconified (InternalFrameEvent e)
    {

    }

    @Override
    public void internalFrameActivated (InternalFrameEvent e)
    {

    }

    @Override
    public void internalFrameDeactivated (InternalFrameEvent e)
    {

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - unknown
    // End of variables declaration//GEN-END:variables
}
