/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applications;

import java.awt.Color;
import java.io.OutputStream;
import java.io.PrintStream;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;
import misc.MDIChild;

/**
 *
 * @author Administrator
 */
public class ConsoleViewGUI extends MDIChild
{
    private class Interceptor extends PrintStream
    {
        Highlighter.HighlightPainter Painter1; 
        
        public Interceptor(OutputStream out, Color c)
        {
            super(out, true);
            Painter1 = new DefaultHighlighter.DefaultHighlightPainter (c);
        }

        @Override
        public void print (String s)
        {
            ConsoleViewGUI.this.strOut(s, Painter1);
        }
        
        @Override
        public void println (String s)
        {
            print(s);
            ConsoleViewGUI.this.strOut("\r\n");
        }
    }

    /**
     * Creates new form LoggerGUI
     */
    public ConsoleViewGUI()
    {
        initComponents();
        setSize (500, 500);
        
        PrintStream origOut = System.out;
        PrintStream origErr = System.err;
        PrintStream interceptor = new Interceptor (origOut, Color.orange);
        PrintStream interceptor2 = new Interceptor (origErr, Color.lightGray);
        System.setOut(interceptor);
        System.setErr(interceptor2);
    }

    public void strOut (String txt, Highlighter.HighlightPainter paint)
    {
        int start = textBox.getCaretPosition();
        int end = start + txt.length();
        strOut (txt);
        Highlighter hl = textBox.getHighlighter();
        try    
        {
            hl.addHighlight(start, end, paint);
        }
        catch (BadLocationException ex)
        {
        }
    }
    
    public void strOut(String txt)
    {
        textBox.append(txt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        textBox = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setResizable(true);
        setTitle("DebugOut");
        setName(""); // NOI18N
        setVisible(true);

        textBox.setEditable(false);
        textBox.setColumns(20);
        textBox.setRows(5);
        jScrollPane1.setViewportView(textBox);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setMinimumSize(new java.awt.Dimension(10, 20));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 30));

        jButton1.setText("CLR");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 337, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jButton1))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        textBox.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textBox;
    // End of variables declaration//GEN-END:variables

    @Override
    public void initAfterDeserialization()
    {
    }
}
