/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applications;

import java.awt.*;
import java.awt.Color;
import java.io.OutputStream;
import java.io.PrintStream;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;
import misc.MDIChild;
import misc.Tools;

/**
 *
 * @author Administrator
 */
public class ConsoleViewGUI extends MDIChild
{
    private class Interceptor extends PrintStream
    {
        Highlighter.HighlightPainter Painter1; 
        
        public Interceptor(OutputStream out, Color c)
        {
            super(out, true);
            Painter1 = new DefaultHighlighter.DefaultHighlightPainter (c);
        }

        @Override
        public void print (String s)
        {
            ConsoleViewGUI.this.strOut(s, Painter1);
        }
        
        @Override
        public void println (String s)
        {
            print(s);
            ConsoleViewGUI.this.strOut("\r\n");
        }
    }

    /**
     * Creates new form LoggerGUI
     */
    public ConsoleViewGUI()
    {
        initComponents();
        setSize (500, 500);
        
        PrintStream origOut = System.out;
        PrintStream origErr = System.err;
        PrintStream interceptor = new Interceptor (origOut, Color.orange);
        PrintStream interceptor2 = new Interceptor (origErr, Color.lightGray);
        System.setOut(interceptor);
        System.setErr(interceptor2);
    }

    public void strOut (String txt, Highlighter.HighlightPainter paint)
    {
        int start = textBox.getCaretPosition();
        int end = start + txt.length();
        strOut (txt);
        Highlighter hl = textBox.getHighlighter();
        try    
        {
            hl.addHighlight(start, end, paint);
        }
        catch (BadLocationException ex)
        {
        }
    }
    
    public void strOut(String txt)
    {
        textBox.append(txt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - unknown
    private void initComponents() {
        jScrollPane1 = new JScrollPane();
        textBox = new JTextArea();
        jPanel1 = new JPanel();
        jButton1 = new JButton();
        jButton2 = new JButton();

        //======== this ========
        setResizable(true);
        setTitle("DebugOut");
        setName("");
        Container contentPane = getContentPane();
        contentPane.setLayout(new BorderLayout());

        //======== jScrollPane1 ========
        {

            //---- textBox ----
            textBox.setEditable(false);
            textBox.setColumns(20);
            textBox.setRows(5);
            jScrollPane1.setViewportView(textBox);
        }
        contentPane.add(jScrollPane1, BorderLayout.CENTER);

        //======== jPanel1 ========
        {

            // JFormDesigner evaluation mark
            jPanel1.setBorder(new javax.swing.border.CompoundBorder(
                new javax.swing.border.TitledBorder(new javax.swing.border.EmptyBorder(0, 0, 0, 0),
                    "JFormDesigner Evaluation", javax.swing.border.TitledBorder.CENTER,
                    javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Dialog", java.awt.Font.BOLD, 12),
                    java.awt.Color.red), jPanel1.getBorder())); jPanel1.addPropertyChangeListener(new java.beans.PropertyChangeListener(){public void propertyChange(java.beans.PropertyChangeEvent e){if("border".equals(e.getPropertyName()))throw new RuntimeException();}});


            //---- jButton1 ----
            jButton1.setText("CLR");
            jButton1.addActionListener(e -> jButton1ActionPerformed(e));

            //---- jButton2 ----
            jButton2.setText("ToClip");
            jButton2.addActionListener(e -> jButton2ActionPerformed(e));

            GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup()
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(0, 259, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup()
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
            );
        }
        contentPane.add(jPanel1, BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        textBox.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        Tools.toClipBoard(textBox.getText());
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - unknown
    private JScrollPane jScrollPane1;
    private JTextArea textBox;
    private JPanel jPanel1;
    private JButton jButton1;
    private JButton jButton2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void initAfterDeserialization()
    {
    }
}
