/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applications;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import misc.MainWindow;
import misc.MDIChild;
import misc.Tools;
import twitter.TwitTools;

/**
 *
 * @author Administrator
 */
public class DirectTweetGUI extends MDIChild implements ActionListener
{
    /**
     * Initializer
     */
    {
        initComponents();
    }

    /**
     * Creates new form DirectTweet
     */
    public DirectTweetGUI()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - unknown
    private void initComponents() {
        jScrollPane1 = new JScrollPane();
        textArea = new JTextArea();
        jPanel1 = new JPanel();
        jButton1 = new JButton();
        jButton7 = new JButton();
        saveName = new JTextField();

        //======== this ========
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("DirectTweet");
        Container contentPane = getContentPane();
        contentPane.setLayout(new BorderLayout());

        //======== jScrollPane1 ========
        {

            //---- textArea ----
            textArea.setColumns(20);
            textArea.setLineWrap(true);
            textArea.setRows(5);
            textArea.setWrapStyleWord(true);
            jScrollPane1.setViewportView(textArea);
        }
        contentPane.add(jScrollPane1, BorderLayout.CENTER);

        //======== jPanel1 ========
        {

            // JFormDesigner evaluation mark
            jPanel1.setBorder(new javax.swing.border.CompoundBorder(
                new javax.swing.border.TitledBorder(new javax.swing.border.EmptyBorder(0, 0, 0, 0),
                    "JFormDesigner Evaluation", javax.swing.border.TitledBorder.CENTER,
                    javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Dialog", java.awt.Font.BOLD, 12),
                    java.awt.Color.red), jPanel1.getBorder())); jPanel1.addPropertyChangeListener(new java.beans.PropertyChangeListener(){public void propertyChange(java.beans.PropertyChangeEvent e){if("border".equals(e.getPropertyName()))throw new RuntimeException();}});

            jPanel1.setLayout(null);

            //---- jButton1 ----
            jButton1.setText("Send");
            jButton1.addActionListener(e -> jButton1ActionPerformed(e));
            jPanel1.add(jButton1);
            jButton1.setBounds(20, 5, 90, 40);

            //---- jButton7 ----
            jButton7.setText("Save as -->");
            jButton7.addActionListener(e -> jButton7ActionPerformed(e));
            jPanel1.add(jButton7);
            jButton7.setBounds(150, 10, 115, jButton7.getPreferredSize().height);

            //---- saveName ----
            saveName.setText("DirectTweet");
            jPanel1.add(saveName);
            saveName.setBounds(280, 10, 192, saveName.getPreferredSize().height);

            { // compute preferred size
                Dimension preferredSize = new Dimension();
                for(int i = 0; i < jPanel1.getComponentCount(); i++) {
                    Rectangle bounds = jPanel1.getComponent(i).getBounds();
                    preferredSize.width = Math.max(bounds.x + bounds.width, preferredSize.width);
                    preferredSize.height = Math.max(bounds.y + bounds.height, preferredSize.height);
                }
                Insets insets = jPanel1.getInsets();
                preferredSize.width += insets.right;
                preferredSize.height += insets.bottom;
                jPanel1.setMinimumSize(preferredSize);
                jPanel1.setPreferredSize(preferredSize);
            }
        }
        contentPane.add(jPanel1, BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        String s = textArea.getText();
        TwitTools.sendLongStringAsync(s);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton7ActionPerformed
    {//GEN-HEADEREND:event_jButton7ActionPerformed
        try
        {
            Tools.serialize(saveName.getText(), this);
            MainWindow.getInstance().initSavesMenu();
        }
        catch (Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - unknown
    private JScrollPane jScrollPane1;
    private JTextArea textArea;
    private JPanel jPanel1;
    private JButton jButton1;
    private JButton jButton7;
    private JTextField saveName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void initAfterDeserialization()
    {
        // Nothing to do
    }

    @Override
    public void actionPerformed (ActionEvent e)
    {

    }
}
