/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applications;

import java.awt.*;
import java.io.IOException;
import java.io.InputStream;
import java.util.concurrent.Future;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import javax.swing.event.*;

import misc.MDIChild;
import misc.ProcessTool;
import misc.Tools;

/**
 *
 * @author Administrator
 */
public class DiskpartGui extends MDIChild
{
    ProcessTool proc = new ProcessTool("diskpart", 1000);
    InputStream inp = proc.getInput();
    Future reader;
    
    /**
     * Creates new form DiskpartGui
     */
    public DiskpartGui()
    {
        initComponents();
        Runnable r = () ->
        {
            while (true)
            {
                try
                {
                    while (inp.available() > 0)                    
                    {
                        char c = (char)inp.read();
                        outField.append(""+c);
                        outField.setCaretPosition(outField.getDocument().getLength());
                    }
                    Thread.sleep(100);
                }
                catch (IOException | InterruptedException ex)
                {
                    System.out.println("bye");
                    return;
                }
            }
        };
        reader = Tools.submit(r);
//        reader = new Thread (r);
//        reader.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - unknown
    private void initComponents() {
        jScrollPane1 = new JScrollPane();
        outField = new JTextArea();
        jButton1 = new JButton();
        jButton2 = new JButton();
        jButton3 = new JButton();
        jButton4 = new JButton();
        jButton5 = new JButton();
        numberField = new JTextField();
        jButton6 = new JButton();
        jButton7 = new JButton();
        directText = new JTextField();
        jButton8 = new JButton();
        jButton9 = new JButton();
        jButton10 = new JButton();
        jButton11 = new JButton();
        jButton12 = new JButton();
        jButton13 = new JButton();
        jButton14 = new JButton();

        //======== this ========
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("DiskPartitioner");
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
                formInternalFrameClosed(e);
            }
        });
        Container contentPane = getContentPane();

        //======== jScrollPane1 ========
        {

            //---- outField ----
            outField.setColumns(20);
            outField.setRows(5);
            jScrollPane1.setViewportView(outField);
        }

        //---- jButton1 ----
        jButton1.setText("help");
        jButton1.addActionListener(e -> jButton1ActionPerformed(e));

        //---- jButton2 ----
        jButton2.setText("listVolume");
        jButton2.addActionListener(e -> jButton2ActionPerformed(e));

        //---- jButton3 ----
        jButton3.setText("listDisk");
        jButton3.addActionListener(e -> jButton3ActionPerformed(e));

        //---- jButton4 ----
        jButton4.setText("listPartition");
        jButton4.addActionListener(e -> jButton4ActionPerformed(e));

        //---- jButton5 ----
        jButton5.setText("selDisk");
        jButton5.addActionListener(e -> jButton5ActionPerformed(e));

        //---- numberField ----
        numberField.setText("0");

        //---- jButton6 ----
        jButton6.setText("selPartition");
        jButton6.addActionListener(e -> jButton6ActionPerformed(e));

        //---- jButton7 ----
        jButton7.setText("selVolume");
        jButton7.addActionListener(e -> jButton7ActionPerformed(e));

        //---- directText ----
        directText.setText("?");
        directText.addActionListener(e -> directTextActionPerformed(e));

        //---- jButton8 ----
        jButton8.setText("detDisk");
        jButton8.addActionListener(e -> jButton8ActionPerformed(e));

        //---- jButton9 ----
        jButton9.setText("detPart");
        jButton9.addActionListener(e -> jButton9ActionPerformed(e));

        //---- jButton10 ----
        jButton10.setText("detVolume");
        jButton10.addActionListener(e -> jButton10ActionPerformed(e));

        //---- jButton11 ----
        jButton11.setText("fileSys");
        jButton11.addActionListener(e -> jButton11ActionPerformed(e));

        //---- jButton12 ----
        jButton12.setText("attrVolume");
        jButton12.addActionListener(e -> jButton12ActionPerformed(e));

        //---- jButton13 ----
        jButton13.setText("attrDisk");
        jButton13.addActionListener(e -> jButton13ActionPerformed(e));

        //---- jButton14 ----
        jButton14.setText("clr");
        jButton14.addActionListener(e -> jButton14ActionPerformed(e));

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 568, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup()
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addComponent(jButton12))
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addGap(160, 160, 160)
                                    .addComponent(jButton7))
                                .addComponent(jButton5)
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addGap(150, 150, 150)
                                    .addComponent(jButton13))
                                .addComponent(jButton3)
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addComponent(jButton4))
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addGap(160, 160, 160)
                                    .addComponent(jButton2))
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addComponent(jButton6))
                                .addComponent(jButton8)
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addComponent(jButton9))
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addGap(140, 140, 140)
                                    .addComponent(jButton10))
                                .addComponent(jButton11))
                            .addGap(9, 9, 9)
                            .addComponent(numberField, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(250, 250, 250)
                            .addComponent(jButton1))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(directText, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jButton14))))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jButton12))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jButton7))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jButton5))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jButton13))
                        .addComponent(jButton3)
                        .addComponent(jButton4)
                        .addComponent(jButton2)
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jButton6))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jButton8))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jButton9))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jButton10))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jButton11))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(numberField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButton1))
                    .addGap(175, 175, 175)
                    .addComponent(directText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton14)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        reader.cancel(true);
        proc.kill();
    }//GEN-LAST:event_formInternalFrameClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        proc.writeln("help");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        proc.writeln("list volume");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        proc.writeln("list disk");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        proc.writeln("list partition");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5ActionPerformed
    {//GEN-HEADEREND:event_jButton5ActionPerformed
        String s = numberField.getText();
        proc.writeln("select disk " + s);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton6ActionPerformed
    {//GEN-HEADEREND:event_jButton6ActionPerformed
        String s = numberField.getText();
        proc.writeln("select partition " + s);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton7ActionPerformed
    {//GEN-HEADEREND:event_jButton7ActionPerformed
        String s = numberField.getText();
        proc.writeln("select volume " + s);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void directTextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_directTextActionPerformed
    {//GEN-HEADEREND:event_directTextActionPerformed
        String s = directText.getText();
        proc.writeln(s);
        directText.setText("");
    }//GEN-LAST:event_directTextActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton8ActionPerformed
    {//GEN-HEADEREND:event_jButton8ActionPerformed
        proc.writeln("detail disk");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton9ActionPerformed
    {//GEN-HEADEREND:event_jButton9ActionPerformed
        proc.writeln("detail partition");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton10ActionPerformed
    {//GEN-HEADEREND:event_jButton10ActionPerformed
        proc.writeln("detail volume");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton11ActionPerformed
    {//GEN-HEADEREND:event_jButton11ActionPerformed
        proc.writeln("filesystems");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton13ActionPerformed
    {//GEN-HEADEREND:event_jButton13ActionPerformed
        proc.writeln("attributes disk");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton12ActionPerformed
    {//GEN-HEADEREND:event_jButton12ActionPerformed
        proc.writeln("attributes volume");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton14ActionPerformed
    {//GEN-HEADEREND:event_jButton14ActionPerformed
        outField.setText("");
    }//GEN-LAST:event_jButton14ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - unknown
    private JScrollPane jScrollPane1;
    private JTextArea outField;
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton3;
    private JButton jButton4;
    private JButton jButton5;
    private JTextField numberField;
    private JButton jButton6;
    private JButton jButton7;
    private JTextField directText;
    private JButton jButton8;
    private JButton jButton9;
    private JButton jButton10;
    private JButton jButton11;
    private JButton jButton12;
    private JButton jButton13;
    private JButton jButton14;
    // End of variables declaration//GEN-END:variables

    @Override
    public void initAfterDeserialization()
    {
    }
}
