/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applications;

import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import javax.swing.event.*;
import inetserver.PittiFtpServer;
import java.awt.Color;
import javax.swing.JInternalFrame;
import misc.Tools;

/**
 *
 * @author Administrator
 */
public class FtpServerGUI extends JInternalFrame
{
    private static final long serialVersionUID = 1L;
    private PittiFtpServer ftp;

    /**
     * Creates new form WebServerGUI
     */
    public FtpServerGUI()
    {
        initComponents();
        button.setBackground(Color.RED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - unknown
    private void initComponents() {
        pathTxt = new JTextField();
        portTxt = new JTextField();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        button = new JToggleButton();
        transmitted = new JLabel();

        //======== this ========
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("FtpServer");
        addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
                formInternalFrameClosed(e);
            }
        });
        Container contentPane = getContentPane();

        //---- pathTxt ----
        pathTxt.setText("C:\\\\");

        //---- portTxt ----
        portTxt.setText("21");

        //---- jLabel1 ----
        jLabel1.setText("BasePath");

        //---- jLabel2 ----
        jLabel2.setText("Port");

        //---- button ----
        button.setText("Start");
        button.addActionListener(e -> buttonActionPerformed(e));

        //---- transmitted ----
        transmitted.setText("0");
        transmitted.setToolTipText("Bytes transferred ...");
        transmitted.setDoubleBuffered(true);
        transmitted.setOpaque(true);

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(34, 34, 34)))
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addComponent(pathTxt)
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(portTxt, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(transmitted, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                            .addComponent(button, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap())
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(pathTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(portTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(transmitted, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 15, Short.MAX_VALUE))
                        .addComponent(button, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
        );
        }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        if (ftp != null)
            ftp.stop();
    }//GEN-LAST:event_formInternalFrameClosed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonActionPerformed
    {//GEN-HEADEREND:event_buttonActionPerformed
        if (button.isSelected())
        {
            button.setText("stop");
            button.setBackground(Color.GREEN);
            ftp = new PittiFtpServer (this, pathTxt.getText(), Integer.parseInt (portTxt.getText()));
            ftp.start();
        }
        else
        {
            button.setText("start");
            button.setBackground(Color.RED);
            ftp.stop();
            ftp = null;
        }
    }//GEN-LAST:event_buttonActionPerformed

    /**
     * Called from webserver worker threads to update counter display
     * @param bytes
     */
    public synchronized void showBytesTransmitted(long bytes)
    {
        transmitted.setText("  "+Tools.humanReadableByteCount (bytes));
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - unknown
    private JTextField pathTxt;
    private JTextField portTxt;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JToggleButton button;
    private JLabel transmitted;
    // End of variables declaration//GEN-END:variables

}
