package applications;

import misc.MDIChild;

import javax.swing.*;
import java.awt.*;

/**
 * Created by Administrator on 7/10/2016.
 */
public class IbanGUI extends MDIChild
{
    private JPanel panel1;
    private JPanel topPanel;
    private JTextField textField1;
    private JTextField textField2;
    private JButton calculateIban;
    private JLabel output;

    public IbanGUI ()
    {
        super();
        this.setContentPane(panel1);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("IBAN Tool");
        setSize(500, 300);
        setVisible(true);
        calculateIban.addActionListener(e -> System.out.println("hello"));
    }

    @Override
    public void initAfterDeserialization ()
    {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$ ()
    {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panel1.setBackground(new Color(-15009758));
        topPanel = new JPanel();
        topPanel.setLayout(new GridBagLayout());
        topPanel.setBackground(new Color(-1700082));
        topPanel.setMinimumSize(new Dimension(0, 100));
        topPanel.setPreferredSize(new Dimension(4, 100));
        topPanel.setRequestFocusEnabled(false);
        panel1.add(topPanel, BorderLayout.NORTH);
        topPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLoweredBevelBorder(), null));
        textField1 = new JTextField();
        textField1.setText("");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        topPanel.add(textField1, gbc);
        final JLabel label1 = new JLabel();
        label1.setForeground(new Color(-16777216));
        label1.setText("KTO:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        topPanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setForeground(new Color(-16777216));
        label2.setText("BLZ:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        topPanel.add(label2, gbc);
        textField2 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        topPanel.add(textField2, gbc);
        calculateIban = new JButton();
        calculateIban.setLabel("Do Calc");
        calculateIban.setText("Do Calc");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        topPanel.add(calculateIban, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 2.0;
        gbc.anchor = GridBagConstraints.WEST;
        topPanel.add(label3, gbc);
        output = new JLabel();
        output.setBackground(new Color(-16777216));
        output.setFont(new Font("Iskoola Pota", output.getFont().getStyle(), 28));
        output.setForeground(new Color(-855544));
        output.setHorizontalAlignment(0);
        output.setOpaque(true);
        output.setPreferredSize(new Dimension(36, 50));
        output.setText("Label");
        panel1.add(output, BorderLayout.SOUTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$ ()
    {
        return panel1;
    }
}
