/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applications;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.Serializable;
import javax.swing.JLabel;
import misc.MainWindow;
import misc.PittiFrame;
import org.scilab.forge.jlatexmath.TeXConstants;
import org.scilab.forge.jlatexmath.TeXFormula;
import org.scilab.forge.jlatexmath.TeXIcon;
import misc.PixelCanvas;
import misc.Tools;

/**
 *
 * @author Administrator
 */
public class LatexGUI extends PittiFrame implements Serializable, ActionListener
{
    public static final long serialVersionUID = 1L;

    /**
     * Object initializer
     */
    {
        initComponents();
    }
    
    /**
     * Creates new form LatexGUI
     */
    public LatexGUI()
    {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        saveName = new javax.swing.JTextField();
        canvas = new PixelCanvas();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("LaTEX");
        setToolTipText("");
        setName(""); // NOI18N
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 90));

        jButton1.setText("Render");
        jButton1.addActionListener(this);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jButton2.setText("to Clipboard");
        jButton2.addActionListener(this);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jButton3.setText("Tweet");
        jButton3.addActionListener(this);
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jButton7.setBackground(new java.awt.Color(255, 255, 0));
        jButton7.setText("Save as -->");
        jButton7.addActionListener(this);
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 115, -1));

        saveName.setText("DirectTweet");
        jPanel1.add(saveName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 192, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        canvas.setBackground(new java.awt.Color(51, 255, 0));
        canvas.setMinimumSize(new java.awt.Dimension(630, 201));
        canvas.setName(""); // NOI18N
        canvas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(canvas, java.awt.BorderLayout.CENTER);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt)
    {
        if (evt.getSource() == jButton7)
        {
            LatexGUI.this.jButton7ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton3)
        {
            LatexGUI.this.jButton3ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton2)
        {
            LatexGUI.this.jButton2ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton1)
        {
            LatexGUI.this.jButton1ActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton7ActionPerformed
    {//GEN-HEADEREND:event_jButton7ActionPerformed
        try
        {
            Tools.serialize(saveName.getText(), this);
            MainWindow.instance.initSavesMenu();
        }
        catch (Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        ((PixelCanvas)canvas).tweet ("test");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        ((PixelCanvas)canvas).toClipboard();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        render();
        invalidate();
        repaint();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void render()
    {
        try
        {
            // get the text
            String latex = textArea.getText();

            // create a formula
            TeXFormula formula = new TeXFormula(latex);

            // render the formla to an icon of the same size as the formula.
            TeXIcon icon = formula
                    .createTeXIcon(TeXConstants.STYLE_DISPLAY, 20);

            // insert a border 
            icon.setInsets(new Insets(5, 5, 5, 5));

            // now create an actual image of the rendered equation
            BufferedImage img = new BufferedImage(icon.getIconWidth(),
                    icon.getIconHeight(), BufferedImage.TYPE_INT_ARGB);
            ((PixelCanvas)canvas).setImage (img);
            Graphics2D g2 = img.createGraphics();
            g2.setColor(Color.WHITE);
            g2.fillRect(0, 0, icon.getIconWidth(), icon.getIconHeight());
            
            JLabel jl = new JLabel();
            jl.setForeground (Color.BLACK);
            icon.paintIcon(jl, g2, 0, 0);
			// at this point the image is created, you could also save it with ImageIO
        }
        catch (Exception ex)
        {
            System.out.println (ex);
        }
    }
    
/*
     \sum_{n=0}^m10^n*a_{n}
     \\---\\
     \sum_{n=0}^m10^n*a_{m-n-1}
*/    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel canvas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField saveName;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables

    @Override
    public void initAfterDeserialization()
    {
        //
    }
}
