package applications;

import misc.MDIChild;
import misc.PixelCanvas;

import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;

/**
 * Created by Administrator on 10/18/2016.
 */
public class PlotWindow extends MDIChild
{
    private JPanel panel1;

    BufferedImage off_Image =
            new BufferedImage(1024, 1024,
                    BufferedImage.TYPE_INT_ARGB);
    Graphics2D g2 = off_Image.createGraphics();

    public void plot (int x, int y)
    {
        g2.drawRect(x, y, 1, 1);
        getPixelCanvas().setImage(off_Image);
        //System.out.println("plot " + x + ":" + y);
    }

    public PlotWindow ()
    {
        super();
        $$$setupUI$$$();
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("BASIC plot window");
        setSize(500, 500);
        setVisible(true);
    }

    public PixelCanvas getPixelCanvas ()
    {
        return (PixelCanvas) panel1;
    }

    @Override
    public void initAfterDeserialization ()
    {

    }

    private void createUIComponents ()
    {
        panel1 = new PixelCanvas();
        panel1.setSize(500, 500);
        panel1.setOpaque(true);
        panel1.setVisible(true);
        panel1.setBackground(Color.BLACK);
        getContentPane().add(panel1, BorderLayout.CENTER);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$ ()
    {
        createUIComponents();
        panel1.setMinimumSize(new Dimension(500, 500));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$ ()
    {
        return panel1;
    }
}
