/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applications;

import java.awt.Component;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JPanel;
import misc.Tools;
import twitter.SingleTweet;
import twitter.TwitTools;
import twitter4j.Status;

/**
 *
 * @author Administrator
 */
public class TimeLineGUI extends javax.swing.JInternalFrame
{

    /**
     * Creates new form TimeLineGUI
     */
    public TimeLineGUI()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemPanel = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(660, 500));
        setVisible(true);

        jButton1.setText("Fetch");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("toClipBrd");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(368, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(0, 0));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 100));

        itemPanel.setMinimumSize(new java.awt.Dimension(100, 1000));
        itemPanel.setPreferredSize(new java.awt.Dimension(100, 100));
        itemPanel.setLayout(new java.awt.GridLayout(0, 1, 5, 5));
        jScrollPane1.setViewportView(itemPanel);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addItem()
    {
        int count = itemPanel.getComponentCount();
        JPanel jp = new SingleTweet();
        Dimension d = jp.getPreferredSize();
        d.height = 5+count*(d.height+5);  // 5 is the Flowlayout Gap
        itemPanel.setPreferredSize(d);
        itemPanel.add(jp);
        revalidate();
        repaint();
    }

    private void delItem()
    {
        Component[] com = itemPanel.getComponents();
        if (com.length == 0)
            return;
        itemPanel.remove(com[0]);
        Dimension d = com[0].getPreferredSize();
        d.height = 5+com.length*(d.height+5);  // 5 is the Flowlayout Gap
        itemPanel.setPreferredSize(d);
        revalidate();
        repaint();
    }
    
    /**
     * Clicked Fetch Button
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        addItem();
//        List<Status> l = TwitTools.getTimeLine();
//        StringBuilder sb = new StringBuilder();
//        l.stream().forEach((status) ->
//        {
//            addItem();
//        });
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * to Clipboard
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        //Tools.toClipBoard(Tools.removeHTML(view.getText()));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void print (String s)
    {
        //view.setText ("<html>"+s+"<br></html>");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel itemPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
