/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applications;

import misc.PittiFrame;
import transform.Base64;
import transform.CRC16CCITT;
import transform.GrayCode;
import transform.MD4;
import transform.MD5;
import transform.Rot13;
import transform.SHA1;
import transform.SHA256;
import transform.Transformation;
import transform.UrlEncode;

/**
 *
 * @author Administrator
 */
public class Transformer extends PittiFrame
{
    Transformation trans;
    
    /**
     * Creates new form Transformer
     */
    public Transformer()
    {
        initComponents();
        trans = new Rot13();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        checkBase64 = new javax.swing.JRadioButton();
        checkMD5 = new javax.swing.JRadioButton();
        checkCRC16 = new javax.swing.JRadioButton();
        encodeButt = new javax.swing.JButton();
        decodeButt = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        clearText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        encText = new javax.swing.JTextArea();
        checkRot13 = new javax.swing.JRadioButton();
        checkSHA1 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(true);

        buttonGroup1.add(checkBase64);
        checkBase64.setText("Base64");
        checkBase64.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkBase64ActionPerformed(evt);
            }
        });

        buttonGroup1.add(checkMD5);
        checkMD5.setText("MD5");
        checkMD5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkMD5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(checkCRC16);
        checkCRC16.setText("CRC16-CCITT");
        checkCRC16.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkCRC16ActionPerformed(evt);
            }
        });

        encodeButt.setText("Encode >>");
        encodeButt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                encodeButtActionPerformed(evt);
            }
        });

        decodeButt.setText("<< Decode");
        decodeButt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                decodeButtActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("SHA256");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("GrayCode");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("MD4");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(encodeButt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 386, Short.MAX_VALUE)
                .addComponent(decodeButt)
                .addGap(99, 99, 99))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBase64)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3)
                    .addComponent(checkCRC16)
                    .addComponent(checkMD5))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBase64)
                    .addComponent(checkMD5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(checkCRC16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encodeButt)
                    .addComponent(decodeButt)))
        );

        jSplitPane1.setDividerLocation(240);
        jSplitPane1.setDividerSize(3);
        jSplitPane1.setToolTipText("Drag left/right");
        jSplitPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        clearText.setColumns(20);
        clearText.setLineWrap(true);
        clearText.setRows(5);
        jScrollPane1.setViewportView(clearText);

        jSplitPane1.setLeftComponent(jScrollPane1);

        encText.setColumns(20);
        encText.setLineWrap(true);
        encText.setRows(5);
        jScrollPane2.setViewportView(encText);

        jSplitPane1.setRightComponent(jScrollPane2);

        buttonGroup1.add(checkRot13);
        checkRot13.setSelected(true);
        checkRot13.setText("Rot13");
        checkRot13.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkRot13ActionPerformed(evt);
            }
        });

        buttonGroup1.add(checkSHA1);
        checkSHA1.setText("SHA1");
        checkSHA1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkSHA1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("URL Enc");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(checkRot13)
                .addGap(30, 30, 30)
                .addComponent(checkSHA1)
                .addGap(46, 46, 46)
                .addComponent(jRadioButton4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkRot13)
                    .addComponent(checkSHA1)
                    .addComponent(jRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBase64ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkBase64ActionPerformed
    {//GEN-HEADEREND:event_checkBase64ActionPerformed
        decodeButt.setEnabled(true);
        trans = new Base64();
    }//GEN-LAST:event_checkBase64ActionPerformed

    private void checkRot13ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkRot13ActionPerformed
    {//GEN-HEADEREND:event_checkRot13ActionPerformed
        decodeButt.setEnabled(true);
        trans = new Rot13();
    }//GEN-LAST:event_checkRot13ActionPerformed

    private void checkSHA1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkSHA1ActionPerformed
    {//GEN-HEADEREND:event_checkSHA1ActionPerformed
        decodeButt.setEnabled(false);
        trans = new SHA1();
    }//GEN-LAST:event_checkSHA1ActionPerformed

    private void checkMD5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkMD5ActionPerformed
    {//GEN-HEADEREND:event_checkMD5ActionPerformed
        decodeButt.setEnabled(false);
        trans = new MD5();
    }//GEN-LAST:event_checkMD5ActionPerformed

    private void checkCRC16ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkCRC16ActionPerformed
    {//GEN-HEADEREND:event_checkCRC16ActionPerformed
        decodeButt.setEnabled(false);
        trans = new CRC16CCITT();
    }//GEN-LAST:event_checkCRC16ActionPerformed

    private void encodeButtActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_encodeButtActionPerformed
    {//GEN-HEADEREND:event_encodeButtActionPerformed
        String s = trans.transform(clearText.getText());
        encText.setText(s);
    }//GEN-LAST:event_encodeButtActionPerformed

    private void decodeButtActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_decodeButtActionPerformed
    {//GEN-HEADEREND:event_decodeButtActionPerformed
        String s = trans.retransform(encText.getText());
        clearText.setText(s);
    }//GEN-LAST:event_decodeButtActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton1ActionPerformed
    {//GEN-HEADEREND:event_jRadioButton1ActionPerformed
        decodeButt.setEnabled(false);
        trans = new SHA256();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton2ActionPerformed
    {//GEN-HEADEREND:event_jRadioButton2ActionPerformed
        decodeButt.setEnabled(false);
        trans = new MD4();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton3ActionPerformed
    {//GEN-HEADEREND:event_jRadioButton3ActionPerformed
        decodeButt.setEnabled(true);
        trans = new GrayCode();
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton4ActionPerformed
    {//GEN-HEADEREND:event_jRadioButton4ActionPerformed
        decodeButt.setEnabled(true);
        trans = new UrlEncode();
    }//GEN-LAST:event_jRadioButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton checkBase64;
    private javax.swing.JRadioButton checkCRC16;
    private javax.swing.JRadioButton checkMD5;
    private javax.swing.JRadioButton checkRot13;
    private javax.swing.JRadioButton checkSHA1;
    private javax.swing.JTextArea clearText;
    private javax.swing.JButton decodeButt;
    private javax.swing.JTextArea encText;
    private javax.swing.JButton encodeButt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void initAfterDeserialization()
    {

    }
}
