package applications;

import com.github.axet.vget.VGet;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import misc.MDIChild;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * Created by Administrator on 7/25/2016.
 */
public class YTDownloaderForm extends MDIChild
{
    private JTextField textField1;
    private JTextField textField2;
    private JButton button1;
    private JPanel mainPanel;

    public YTDownloaderForm ()
    {
        super();
        this.setContentPane(mainPanel);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("YT Downloader");
        setSize(400, 110);
        setVisible(true);
    }

    public static void main (String[] args)
    {
        //new YTDownloaderForm();
//        JFrame frame = new JFrame("YTDownloaderForm");
//        frame.setContentPane(new YTDownloaderForm().mainPanel);
//        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        frame.setSize(400, 110);
//        frame.setVisible(true);
    }

    @Override
    public void initAfterDeserialization ()
    {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$ ()
    {
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:d:grow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        mainPanel.setMinimumSize(new Dimension(100, 142));
        final JLabel label1 = new JLabel();
        label1.setFont(new Font(label1.getFont().getName(), label1.getFont().getStyle(), 20));
        label1.setText("Url:");
        CellConstraints cc = new CellConstraints();
        mainPanel.add(label1, cc.xy(1, 1));
        textField1 = new JTextField();
        textField1.setMinimumSize(new Dimension(100, 31));
        textField1.setPreferredSize(new Dimension(400, 31));
        mainPanel.add(textField1, cc.xy(3, 1));
        final JLabel label2 = new JLabel();
        label2.setFont(new Font(label2.getFont().getName(), label2.getFont().getStyle(), 20));
        label2.setText("Path:");
        mainPanel.add(label2, cc.xy(5, 1));
        textField2 = new JTextField();
        textField2.setMinimumSize(new Dimension(50, 31));
        textField2.setPreferredSize(new Dimension(400, 31));
        mainPanel.add(textField2, cc.xy(7, 1));
        button1 = new JButton();
        button1.setLabel("DoIt");
        button1.setText("DoIt");
        mainPanel.add(button1, cc.xy(5, 3));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$ ()
    {
        return mainPanel;
    }

    //    public static void main (String[] args) throws MalformedURLException
//    {
//        String url = "https://www.youtube.com/watch?v=TPzIWRsbNwE";
//        String path = "c:\\test\\";
//        VGet v = new VGet(new URL(url), new File(path));
//        v.download();
//    }
}
